export const userReports = [
  {
    id: 1,
    type: 'subject-inc',
    status: 'processing',
    title: 'I have concerns regarding my subject, MMW',
    updated: '2 days ago',
    created: 'April 1, 2022',
    author: 'Eman Martin',
    description: 'What is device encryption? Device encryptionis a feature that exists in Windows 10 & 11. It is available on PCs that are connected to the internet and signed into a Microsoft Account. Your device needs to have a TPM and Secure Boot',
    helpful: 0,
    comment: 3,
  },
  {
    id: 2,
    type: 'failed-subject',
    status: 'pending',
    title: 'I failed my subject last semester, PAL',
    updated: '1 day ago',
    created: 'April 22, 2022',
    author: 'Catheryn Jay Magkey',
    description: 'The following release notes coincide with the Cumulative updates for all the supported versions of Windows, for the month of April 2022.Windows 11Windows 11 (original release): KB5012592 Build 22000.613April 12, 2022—KB5012592 (OS Build 22000.613)',
    helpful: 1,
    comment: 2,
  },
  {
    id: 3,
    type: 'remaining-balance',
    status: 'processing',
    title: 'Last month, I have a balance of 1000.00 pesos',
    updated: '3 days ago',
    created: 'April 20, 2022',
    author: 'Cherry Mae Recin2',
    description: 'AdvancedApplies to: Windows 10/11A detailed explanation of what Device Encryption is, can be found here: What is device encryption, and should I use it? - Microsoft CommunityBitlocker uses the same technology but has more advanced features.Why',
    helpful: 0,
    comment: 4,
  },
  {
    id: 4,
    type: 'add-subject',
    status: 'pending',
    title: 'Greetings, I would like to add a subject for this current semester.',
    updated: '1 day ago',
    created: 'April 22, 2022',
    author: 'Dwain Magracia',
    description: 'I have had this error now for about 2 weeks and have tried everything in the forums. I need help please. Setup is : Windows 11 (just upgraded), MSI B450 Gaming PLUS, CPU Ryzen 2700x, Nvidia EVGA GEFORCE 3060 12GB, G.Skill Trident Z RGB Series 16GB (2 x 8GB)',
    helpful: 0,
    comment: 0,
  },
  {
    id: 5,
    type: 'change-subject',
    status: 'completed',
    title: 'Greetings, I would like to change a subject this current semester.',
    updated: '1 day ago',
    created: 'April 22, 2022',
    author: 'Franz Mallari',
    description: 'Hello, when I play games, there is a 90% chance that BSOD will occur.Here is my windows minidump content, may you analyze it for me?Thanks a lot.Microsoft (R) Windows Debugger Version 10.0.22549.1000 AMD64 Copyright (c) Microsoft Corporation. All rights reserved.',
    helpful: 0,
    comment: 0,
  },
  {
    id: 6,
    type: 'prev-sem',
    status: 'completed',
    title: 'I would like to report a subject from the previous semester.',
    updated: '6 day ago',
    created: 'April 18, 2022',
    author: 'Masahiro Yokomizo',
    description: 'I have been using free Avast Antivirus for protection against viruses, for almost 3 years. But I am planning to buy a premium subscription, given it appears to be having cool features now, such as a driver updater, webcam protection etc.What I am concerned',
    helpful: 1,
    comment: 8,
  },
  {
    id: 8,
    type: 'curr-sem',
    status: 'completed',
    title: 'I have a question regarding the availabity of a subject this current semester.',
    updated: '5 day ago',
    created: 'April 19, 2022',
    author: 'Franz Mallari',
    description: 'HiI have a Toshiba Satellite laptop that came with Windows 8 when I purchased it new. There was a recovery drive. I wanted to wipe it clean for my nephew but something went wrong and now there is an error saying no boot device. I need to reinstall Windows but the',
    helpful: 1,
    comment: 9,
  },
]